src/Entity/Facture.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FactureRepository")
 */
class Facture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="date")
     */
    private $date_edition;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_echeance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_facture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="factures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Etat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDateEdition(): ?\DateTimeInterface
    {
        return $this->date_edition;
    }

    public function setDateEdition(\DateTimeInterface $date_edition): self
    {
        $this->date_edition = $date_edition;

        return $this;
    }

    public function getDateEcheance(): ?\DateTimeInterface
    {
        return $this->date_echeance;
    }

    public function setDateEcheance(?\DateTimeInterface $date_echeance): self
    {
        $this->date_echeance = $date_echeance;

        return $this;
    }

    public function getNumeroFacture(): ?string
    {
        return $this->numero_facture;
    }

    public function setNumeroFacture(string $numero_facture): self
    {
        $this->numero_facture = $numero_facture;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat;
    }

    public function setEtat(string $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }
}

src/Entity/Subscription.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SubscriptionRepository")
 */
class Subscription
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=11)
     */
    private $cpu;

    /**
     * @ORM\Column(type="integer")
     */
    private $ram;

    /**
     * @ORM\Column(type="integer")
     */
    private $disk_space;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $remise;

    /**
     * @ORM\Column(type="date")
     */
    private $date_sub;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="subscriptions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Services", inversedBy="subscriptions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_services;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sub_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ip_adresse;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $high_availability;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $options;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $IP;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $backup;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCpu(): ?string
    {
        return $this->cpu;
    }

    public function setCpu(string $cpu): self
    {
        $this->cpu = $cpu;

        return $this;
    }

    public function getRam(): ?int
    {
        return $this->ram;
    }

    public function setRam(int $ram): self
    {
        $this->ram = $ram;

        return $this;
    }

    public function getDiskSpace(): ?int
    {
        return $this->disk_space;
    }

    public function setDiskSpace(int $disk_space): self
    {
        $this->disk_space = $disk_space;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getRemise(): ?float
    {
        return $this->remise;
    }

    public function setRemise(?float $remise): self
    {
        $this->remise = $remise;

        return $this;
    }

    public function getDateSub(): ?\DateTimeInterface
    {
        return $this->date_sub;
    }

    public function setDateSub(\DateTimeInterface $date_sub): self
    {
        $this->date_sub = $date_sub;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }
 
    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdServices(): ?Services
    {
        return $this->id_services;
    }

    public function setIdServices(?Services $id_services): self
    {
        $this->id_services = $id_services;

        return $this;
    }

    public function getSubName(): ?string
    {
        return $this->sub_name;
    }

    public function setSubName(string $sub_name): self
    {
        $this->sub_name = $sub_name;

        return $this;
    }

    public function getIpAdresse(): ?string
    {
        return $this->ip_adresse;
    }

    public function setIpAdresse(string $ip_adresse): self
    {
        $this->ip_adresse = $ip_adresse;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getHighAvailability(): ?string
    {
        return $this->high_availability;
    }

    public function setHighAvailability(?string $high_availability): self
    {
        $this->high_availability = $high_availability;

        return $this;
    }

    public function getOptions(): ?string
    {
        return $this->options;
    }

    public function setOptions(?string $options): self
    {
        $this->options = $options;

        return $this;
    }

    public function getIP(): ?string
    {
        return $this->IP;
    }

    public function setIP(?string $IP): self
    {
        $this->IP = $IP;

        return $this;
    }

    public function getBackup(): ?string
    {
        return $this->backup;
    }

    public function setBackup(?string $backup): self
    {
        $this->backup = $backup;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "'{{ value }}' n'est pas une adresse mail valide."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * 
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *      min = 14,
     *      max = 14,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $num_siret;

    /**
     * @ORM\Column(type="date")
     */
    private $date_inscription;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $forme_juridique;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex( 
     *                  "/^[0-9]{5}$/"
     * )
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $society_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Facture", mappedBy="id_user")
     */
    private $factures;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Subscription", mappedBy="id_user")
     */
    private $subscriptions;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TVA", inversedBy="users")
     */
    private $id_tva;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $remise;
    
    public function __construct()
    {
        $this->factures = new ArrayCollection();
        $this->subscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getNumSiret(): ?string
    {
        return $this->num_siret;
    }

    public function setNumSiret(?string $num_siret): self
    {
        $this->num_siret = $num_siret;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getFormeJuridique(): ?string
    {
        return $this->forme_juridique;
    }

    public function setFormeJuridique(string $forme_juridique): self
    {
        $this->forme_juridique = $forme_juridique;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getNumeroTel(): ?string
    {
        return $this->numero_tel;
    }

    public function setNumeroTel(?string $numero_tel): self
    {
        $this->numero_tel = $numero_tel;

        return $this;
    }

    public function getSocietyName(): ?string
    {
        return $this->society_name;
    }

    public function setSocietyName(?string $society_name): self
    {
        $this->society_name = $society_name;

        return $this;
    }

    /**
     * @return Collection|Facture[]
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures[] = $facture;
            $facture->setIdUser($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->contains($facture)) {
            $this->factures->removeElement($facture);
            // set the owning side to null (unless already changed)
            if ($facture->getIdUser() === $this) {
                $facture->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Subscription[]
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function addSubscription(Subscription $subscription): self
    {
        if (!$this->subscriptions->contains($subscription)) {
            $this->subscriptions[] = $subscription;
            $subscription->setIdUser($this);
        }

        return $this;
    }

    public function removeSubscription(Subscription $subscription): self
    {
        if ($this->subscriptions->contains($subscription)) {
            $this->subscriptions->removeElement($subscription);
            // set the owning side to null (unless already changed)
            if ($subscription->getIdUser() === $this) {
                $subscription->setIdUser(null);
            }
        }

        return $this;
    }

    public function getIdTva(): ?TVA
    {
        return $this->id_tva;
    }

    public function setIdTva(?TVA $id_tva): self
    {
        $this->id_tva = $id_tva;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getRemise(): ?float
    {
        return $this->remise;
    }

    public function setRemise(?float $remise): self
    {
        $this->remise = $remise;

        return $this;
    }
}

templates/pages/facture.html.twig
<link rel="stylesheet" href="dist/css/bootstrap.css" >
<link rel="stylesheet" href="dist/css/style.css" media="all" />

      <p class="flotte">
        <img src="dist/img/logo1.png"/></p>
      <p style="line-height:65px;font-size:26px;margin-left:300px">
        Facture n°{{factureId.numeroFacture}}</p>
        <hr>
      <div style="margin-top:100px;">
        <div class="text-right position-absolute" id="company">
          <div>CloudMe</div>
          <div>455 Foggy Heights,<br /> AZ 85004, US</div>
          <div>03 20 20 20 20</div>
          <div><a href="mailto:cloudme@example.com">cloudme@example.com</a></div>
        </div>
        <div class="text-left" style="font-size:18px" id="project">
          <div style="font-size:24px">Information client</div>
          <div><span>CLIENT</span> {{app.user.name}} {{app.user.firstName}}</div>
          <div><span>ADDRESS</span> {{app.user.adresse}},{{app.user.ville}}</div>
          <div><span>EMAIL</span> <a href="mailto:{{app.user.email}}">{{app.user.email}}</a></div>
          <div><span>Date de facturation:</span> {{factureId.dateEdition | date('d/m/Y')}}</div>
          <div><span>Somme prélevée à partir</span> {{factureId.dateEcheance | date('d/m/Y')}}</div>
        </div>
      </div>
      <table style="margin-top:190px;font-size:20px;">
          <tr>
            <th style="width: 10%">Référence</th>
            <th >Désignation</th>
            <th style="width: 5%">Qte</th>
            <th style="width: 10%">PU HT</th>
            <th style="width: 10%">Total HT</th>
          </tr>
          {% for data in userSub %}
        <tbody>
          <tr>
            <td>{{data.subname | upper}}</td>
            <td>{{data.headline}} du {{data.dateSub | date('d/m/Y')}} au {{data.lastDays | date('d/m/Y')}}</td>
            <td>1</td>
            <td>{{data.price * 1}}€</td>
            <td>{{data.price}}€</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
      
      <table style="width:45%;font-size:18px; margin-left:294%;">
          <tr>
            <th scope="col">Total HT</th>
            <th scope="col">Taux TVA</th>
            <th scope="col">Total TVA</th>
            <th scope="col">Total TTC</th>
          </tr>
        <tbody>
           <tr>
            <td>{{totalPrice}}€</td>
            <td>20,00%</td>
            <td>{{totalPrice * tva.taux}}€</td>
            <td>{{totalPrice * (tva.taux + 1)}}€</td>
          </tr> 
        </tbody>
      </table>
    <footer>
    Invoice was created on a computer and is valid without the signature and seal.
    </footer>

templates/pages/home.html.twig
  <!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->

    <!-- /.content-header -->
   <section class="content">
      <div class="container-fluid">
        <!-- /.row -->
        <h1 class="text-center"> Bonjour {{app.user.name}} {{app.user.firstName}}</h1>
        <hr>
        {% if souscription %}
      <div class="row mt-4 justify-content-center text-right">
          <div class="col-12 col-sm-4 col-md-3">
            <div class="info-box">
              <span class="info-box-icon bg-primary elevation-1"><i class="fas fa-cog"></i></span>
              <div class="info-box-content">
                <span class="info-box-text text-center">CPU(Global)</span>
                <span class="info-box-text">Capacité</span>
                <span class="info-box-number">
                  {{ CPU }} / {{ maxCpu }}
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-4 col-md-3">
            <div class="info-box mb-4">
              <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-memory"></i></span>

              <div class="info-box-content">
                <span class="info-box-text text-center">RAM (Global) </span>
                <span class="info-box-text">Capacité</span>
                <span class="info-box-number">{{ RAM }}/{{ maxRam }} GB</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <!-- fix for small devices only -->
          <div class="clearfix hidden-md-up"></div>

          <div class="col-12 col-sm-4 col-md-3">
            <div class="info-box mb-4">
              <span class="info-box-icon bg-dark elevation-1"><i class="fas fa-hdd"></i></span>

              <div class="info-box-content">
                <span class="info-box-text text-center">Disque(Global)</span>
                <span class="info-box-text">Capacité</span>
                <span class="info-box-number">
                {{ Disque }} / {{ maxDisk }} GB
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
      </div>
      <div class="col-md-9 mr-auto ml-auto">
        <table class="table table-head-fixed table-striped table-hover table-bordered table-sm">
                  <thead>
                    <tr>
                      <th>Nom</th>
                      <th>Headline</th>
                      <th>Type</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for allSub in souscription %}
                    <tr class="tabAccueil" data-id="{{ allSub.id }}" data-target ="info" data-class="{{ allSub.type }}" style="cursor: pointer">
                      <td>{{ allSub.name }}</td>
                      <td>{{ allSub.headline }}</td>
                      <td>{{ allSub.type }}</td>
                      {% if allSub.status == 1 %}
                      <td class="text-danger text-center"><i class="fas fa-times-circle"></i></td>
                      {% else %}
                      <td class="text-success text-center"><i class="fas fa-check"></i></td>
                      {% endif %}
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            {% else %}
            <h1 class="text-center">Vous n'avez souscris à aucun service</h1>
            {% endif %}
          <!-- ./col -->
  <script src='js/Nav.js'></script>
  <script>
    $(document).ready(function(){
      $('.toast').toast('show');
    });
</script>

templates/pages/infoFacture.html.twig
<div class="col-10 ml-auto mr-auto">
  <i id="loupeDisplay" class="fas fa-search mt-2 mb-2" aria-hidden="true"></i>
</div>
<table class="table table-striped mx-auto" style="width:90%">
  <thead>
    <tr id="liste">
      <th scope="col-sm-3" data-search="numero_facture">N°facture</th>
      <th scope="col-sm-3" data-search="date_edition">Date édition</th>
      <th scope="col-sm-3">Type de paiement</th>
      <th scope="col-sm-3">Etat</th>
      <th scope="col-sm-3">Total TTC</th>
      <th scope="col-sm-3">Export</th>
    </tr>
  </thead>
  {% for facture in factures %}
  <tbody>
    <tr>
      <th>{{facture.numeroFacture}}</th>
      <td>{{facture.dateEdition | date('d/m/Y')}}</td>
      <td>CB</td>
      <td>{% if facture.etat == "Payé" %}
      <span class="badge badge-success">
      {% elseif facture.etat == "En attente" %}
      <span class="badge badge-warning">
      {% else %}
      <span class="badge badge-danger">
      {% endif %}
      {{facture.etat}}</span></td>
      
      <td>{{facture.price * (tva.taux + 1) }}€</td>
      <td><a href="{{path('facture', {'id':facture.id}) }}">
        <i class="fas fa-file-pdf"></i> PDF
        </a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination justify-content-center">
  {{ knp_pagination_render(factures) }}
  </div>
<script src="js/pagination.js"></script>

templates/pages/infoMetrics.html.twig
<h1> Gros metrics </h1>

templates/pages/monProfil.html.twig
<style>
body{
    margin-top:20px;
    background:#f8f8f8
}
</style>
<div class="container">

  <div class="col">
    <div class="row">
      <div class="col mb-3">
        <div class="card">
          <div class="card-body">
            <div class="e-profile">
                <div class="text-right">
                    <div><small>Membre depuis le {{app.user.dateInscription|date('d/m/Y')}}</small></div>
                </div>
                {{ form_start(formProfil) }}
                {{ form_widget(formProfil._token) }}
              <div class="tab-content pt-3">
                <div class="tab-pane active">
                    <div class="row">
                      <div class="col">
                        <div class="row">
                          <div class="col">
                            <label>Nom de l'entreprise</label>
                            {{ form_row(formProfil.society_name) }}
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              <label>Nom</label>
                              {{ form_row(formProfil.name) }}
                          </div>
                          <div class="col">
                              <label>Prenom</label>
                              {{ form_row(formProfil.first_name) }}
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              <label>Email</label>
                              {{ form_row(formProfil.email) }}
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              <label>Adresse</label>
                              {{ form_row(formProfil.adresse) }}
                          </div>
                        </div>
                    </div>
                      <div class="col-12 col-sm-6 mb-3">
                          <div class="row">
                            <div class="col">
                              <label>Forme Juridique</label>
                                {{ form_row(formProfil.forme_juridique) }}
                            </div>
                            <div class="col">
                              <label>Numéro de SIRET</label>
                              {{ form_row(formProfil.num_siret) }}
                            </div>
                          </div>
                          <div class="col">
                              <label>Numero de téléphone</label>
                              {{ form_row(formProfil.numero_tel) }}
                        </div>
                        <div class="col">
                              <label>Pays</label>
                              {{ form_row(formProfil.pays) }}
                        </div>
                        <div class="row">
                          <div class="col">
                              <label>Code Postal</label>
                              {{ form_row(formProfil.codePostal) }}
                          </div>
                          <div class="col">
                              <label>Ville</label>
                              {{ form_row(formProfil.ville) }}
                          </div>
                        </div>
                      <div class="col d-flex justify-content-end">
                        <button class="btn btn-primary" type="submit">Sauvegarder</button>
                    </div>
                    {{ form_start(formProfil) }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

  </div>
</div>
</div>